# Generated by Django 5.2.7 on 2025-11-04 02:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('MIE', 'Miércoles'), ('DOM', 'Domingo')], max_length=3)),
                ('hora', models.TimeField()),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='academia.curso')),
            ],
        ),
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_mesa', models.CharField(blank=True, max_length=100)),
                ('facilitador', models.ForeignKey(limit_choices_to={'role': 'FACILITADOR'}, on_delete=django.db.models.deletion.PROTECT, related_name='mesas_asignadas', to=settings.AUTH_USER_MODEL)),
                ('horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mesas', to='academia.horario')),
            ],
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('telefono', models.CharField(blank=True, max_length=15)),
                ('colonia', models.CharField(blank=True, max_length=100)),
                ('calle', models.CharField(blank=True, max_length=100)),
                ('numero_casa', models.CharField(blank=True, max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('mesa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alumnos', to='academia.mesa')),
            ],
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_clase', models.DateField()),
                ('numero_clase', models.PositiveSmallIntegerField()),
                ('estado', models.CharField(choices=[('A', 'Asistió'), ('F', 'Faltó'), ('R', 'Recuperó'), ('D', 'Adelantó')], max_length=1)),
                ('motivo_falta_recupero', models.TextField(blank=True, null=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='academia.alumno')),
                ('horario_adelanto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academia.horario')),
            ],
            options={
                'unique_together': {('alumno', 'numero_clase')},
            },
        ),
    ]
