# Generated by Django 5.2.8 on 2025-11-07 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asistencia',
            name='fecha_clase',
        ),
    ]
