# Generated by Django 5.2.8 on 2025-11-08 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0002_remove_asistencia_fecha_clase'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesa',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
