# Generated by Django 5.2.8 on 2025-11-09 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0003_mesa_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='horario',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
