# Generated by Django 5.2.8 on 2025-11-14 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0004_horario_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='areas_mejorar',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='alumno',
            name='bautizado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alumno',
            name='meta_personal',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='alumno',
            name='testimonio',
            field=models.TextField(blank=True, default=''),
        ),
    ]
